version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser"
  ]

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = [".devcontainer/experimental/Dockerfile"]

[[transformers]]
name = "prettier"

[[transformers]]
name = "rubocop"
