---
title: OpenINF Portal
email: code@inf.is
description: Aggregate, curate, disseminate, and apply information derived from
  diverse sources.
baseurl: ''
url: https://open.inf.is
twitter_username: OpenINF
github_username: OpenINF
repository: OpenINF/open.inf.is

# Site build settings
markdown: kramdown
plugins:
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-seo-tag

## Content collections
# @see https://jekyllrb.com/docs/collections
collections_dir: collections
collections:
  authors:
    output: true
  docs:
    permalink: :collection/:path
    output: true
  pages:
    output: true
  posts:
    permalink: news/:year/:month/:day/:title
    output: true
defaults:
  - scope:
      path: _pages
      type: pages
    values:
      ##
      # @see https://github.com/OpenINF/open.inf.is/blob/HEAD/_layouts/default.html
      layout: default
      locale: en
  - scope:
      path: _layouts
      type: pages
    values:
      ##
      # @see https://github.com/OpenINF/open.inf.is/blob/HEAD/_layouts/default.html
      layout: default
  - scope:
      path: _docs
      type: docs
    values:
      ##
      # @see https://github.com/OpenINF/open.inf.is/blob/HEAD/_layouts/docs.html
      layout: docs
      editable: true
      toc: true
      breadcrumbs: true
      body_classes:
        - hide-butterbar
  - scope:
      path: _posts
      type: posts
    values:
      ##
      # @see https://github.com/OpenINF/open.inf.is/blob/HEAD/_layouts/news_item.html
      layout: news_item
      editable: true
      toc: true
      breadcrumbs: true
      body_classes:
        - hide-butterbar

# To be sure Jekyll "sees" and processes the files inside of a new collection.
include: ['collections/_pages']

# Exclude from processing.
exclude:
  - AUTHORS
  - bin/
  - biome.jsonc
  - build/
  - CNAME
  - cspell.json
  - dprint.json
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules/
  - package-scripts.yml
  - package.json
  - pnpm-lock.yaml
  - project-terms.txt
  - README.md
  - tmp/
  - tools/
  - vendor/
